=== ricardobar96/ricardo_LND/TRIM2/UD5/DOSSIER/libreria.dtd
<!-- DTD created at Wed Jan 13 16:14:00 GMT 2021 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT libreria (libros)>
<!ELEMENT libros (libro)+>
<!ELEMENT libro (titulo, autor, editorial)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ATTLIST tag  attribute CDATA #REQUIRED>

=== ricardobar96/ricardo_LND/TRIM2/UD5/DOSSIER/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE libreria SYSTEM "libreria.dtd">
<libreria>
  <libros>
    <libro>
      <titulo>El MÃ©dico</titulo>
      <autor>Noah Gordon</autor>
      <editorial>Salamandra</editorial>
    </libro>
    <libro>
      <titulo>Harry Potter</titulo>
      <autor>J.K Rowling</autor>
      <editorial>Salamandra</editorial>
    </libro>
  </libros>
</libreria>
