=== ricardobar96/ricardo_LND/TRIM2/UD5/TAREAS/Tarea 5.3/pedidos.dtd
<!-- DTD created at Wed Feb 03 16:06:20 GMT 2021 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT pedidos (cliente+, articulo+, pedido+)>
<!ATTLIST cliente idCliente ID #REQUIRED>
<!ELEMENT cliente (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ATTLIST articulo idArticulo ID #REQUIRED>
<!ELEMENT articulo (nombre, descripcion?)>
<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST pedido idPedido ID #REQUIRED>
<!ATTLIST pedido refCliente IDREF #REQUIRED>
<!ELEMENT pedido (articuloPedido, metodoPago, direccion)>
<!ATTLIST articuloPedido precio CDATA "1">
<!ATTLIST articuloPedido refArticulo IDREF #REQUIRED>
<!ELEMENT articuloPedido EMPTY>
<!ELEMENT metodoPago (tarjeta | transferencia)>
<!ATTLIST tarjeta titular IDREF #REQUIRED>
<!ELEMENT tarjeta (numero, fechaCaducidad, banco)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT fechaCaducidad (#PCDATA)>
<!ELEMENT banco (#PCDATA)>
<!ELEMENT transferencia (banco, numeroCuenta)>
<!ELEMENT numeroCuenta (#PCDATA)>
<!ELEMENT direccion (provincia, poblacion, calle, numero)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT calle (#PCDATA)>

=== ricardobar96/ricardo_LND/TRIM2/UD5/TAREAS/Tarea 5.3/pedidos_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">
<pedidos>
	<cliente idCliente="cli01">
		<nombre>Luz</nombre>
		<apellidos>Pérrez</apellidos>
	</cliente>
	<cliente idCliente="cli02">
		<nombre>Miranda</nombre>
		<apellidos>Gabriel</apellidos>
	</cliente>
	<articulo idArticulo="art01">
		<nombre>papas</nombre>
		<descripcion>saco de papas</descripcion>
	</articulo>
	<articulo idArticulo="art02">
		<nombre>boniatos</nombre>
		<descripcion>saco de batatas</descripcion>
	</articulo>
	<pedido idPedido="ped01" refCliente="cli01">
		<articuloPedido precio="1001" refArticulo="art01"/>
		<metodoPago>
			<tarjeta titular="cli01">
				<numero>123456789</numero>
				<fechaCaducidad>01-01-2018</fechaCaducidad>
				<banco/>
			</tarjeta>
		</metodoPago>
		<direccion>
			<provincia/>
			<poblacion/>
			<calle/>
			<numero/>
		</direccion>
	</pedido>
	<pedido idPedido="ped02" refCliente="cli02">
		<articuloPedido precio="1002" refArticulo="art02"/>
		<metodoPago>
			<tarjeta titular="cli02">
				<numero/>
				<fechaCaducidad/>
				<banco/>
			</tarjeta>
		</metodoPago>
		<direccion>
			<provincia/>
			<poblacion/>
			<calle/>
			<numero/>
		</direccion>
	</pedido>
	<pedido idPedido="ped03" refCliente="cli02">
		<articuloPedido precio="1003" refArticulo="art02"/>
		<metodoPago>
			<tarjeta titular="cli02">
				<numero/>
				<fechaCaducidad/>
				<banco/>
			</tarjeta>
		</metodoPago>
		<direccion>
			<provincia/>
			<poblacion/>
			<calle/>
			<numero/>
		</direccion>
	</pedido>
</pedidos>
